services:
  - type: web
    runtime: node
    name: multitenant-saas
    region: frankfurt
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    numInstances: 1
    healthCheckTimeout: 300 